### ISSUE TITLE
Crash without public/js and views folder

### ISSUE THREAD

**Issue by pautasso** [souhailaS/ejs-compile#3]
If the folders
```
views/
public/js
```
do not exist, it will crash instead of returning an error message

**Comment by souhailaS** [comment]
resolved. 

- If no "views" folder or no ejs files in the "views"  are found the error is caught and a clear message is logged:

```
console.error(`\n|--- Compilation Failed: ${error.message}`.red);
console.error(
      `|--- Ensure the "views" directory exists and contains .ejs files.`.red
    );
```

- if public/js directory is missing it is going to be created:

```
if (!fs.existsSync(resolvedOutputDir)) {
  fs.mkdirSync(resolvedOutputDir, { recursive: true });
}
```
